"""PRJ226 Agent Runner package."""

from prj226_runner.errors import (
    AgentExecutionError,
    ArtifactValidationError,
    GovernanceBlockerError,
    ImplementationFailureError,
    ReviewStaleError,
    RunnerEnvironmentError,
    RunnerError,
    WorktreeIntegrityError,
)
from prj226_runner.models import (
    AgentConfig,
    ErrorClass,
    EventRecord,
    RunManifest,
    RunState,
    RunStateSnapshot,
)
from prj226_runner.reviewer_profile import (
    CODEX_REVIEWER_MODEL,
    CODEX_REVIEWER_PROVIDER,
    CodexReviewerProfile,
    build_codex_reviewer_profile,
    reviewer_profile_hash,
)
from prj226_runner.paths import (
    DEFAULT_CANONICAL_BRANCH,
    DEFAULT_EXPECTED_HEAD,
    DEFAULT_EXPECTED_TREE,
    DEFAULT_TARGET_REPO,
    get_config_dir,
    get_roles_dir,
    get_run_dir,
    get_runtime_root,
    get_runner_root,
    get_runs_dir,
    get_schemas_dir,
    get_target_repo_path,
    get_templates_dir,
)

__version__ = "0.1.0"

__all__ = [
    "__version__",
    "RunState",
    "ErrorClass",
    "AgentConfig",
    "RunManifest",
    "RunStateSnapshot",
    "EventRecord",
    "CODEX_REVIEWER_PROVIDER",
    "CODEX_REVIEWER_MODEL",
    "CodexReviewerProfile",
    "build_codex_reviewer_profile",
    "reviewer_profile_hash",
    "RunnerError",
    "RunnerEnvironmentError",
    "AgentExecutionError",
    "ArtifactValidationError",
    "ImplementationFailureError",
    "GovernanceBlockerError",
    "ReviewStaleError",
    "WorktreeIntegrityError",
    "DEFAULT_TARGET_REPO",
    "DEFAULT_CANONICAL_BRANCH",
    "DEFAULT_EXPECTED_HEAD",
    "DEFAULT_EXPECTED_TREE",
    "get_runner_root",
    "get_runs_dir",
    "get_run_dir",
    "get_runtime_root",
    "get_schemas_dir",
    "get_roles_dir",
    "get_templates_dir",
    "get_config_dir",
    "get_target_repo_path",
]
